Awall sentry
splitio/pipelinewise pull request #3
Opened 2020-06-22 16:43 UTC by awall1010

Added sentry as singer connector and added requirements

2020-06-22 17:11 UTC, pmasse requested changes

2020-06-22 17:11 UTC, pmasse commented on singer-connectors/tap-fastly/requirements.txt
> +-e git://github.com/splitio/tap-fastly.git@awall-tap-fastly#egg=tap-fastly
I don't think this should go in.

2020-06-22 17:11 UTC, pmasse commented on pipelinewise/cli/pipelinewise.py
> +                selected = table_meta.get('selected', False) #gets something from metadata to decide if sync or not
I don't think this should go in

2020-06-22 17:11 UTC, pmasse commented on pipelinewise/cli/pipelinewise.py
> +            singer_stream_ids
I don't think this should go in

2020-06-22 17:11 UTC, pmasse commented on install.sh
> +    tap-mysql
You should not uncomment that. It caused issues with the build

2020-06-22 17:11 UTC, pmasse commented on install.sh
> -    #target-s3-csv
Just add tap-sentry but don't uncomment the other. It caused some issues with the build

2020-06-22 20:35 UTC, awall1010 reviewed
re commented out connectors and fixed fastly requirements

2020-07-14 00:18 UTC, pmasse approved these changes

2020-07-14 00:19 UTC, merged